### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by makoeppel** [pekraem/Datenanalyse#1]
Hi Peter,

kannst du mir Rechte geben zum Sachen hochladen?

Gruß
Marius

**Comment by JoergSchindler** [comment]
Hey,

Ich bin ein Kumpel von Marius der den Kurs auch macht. Hätte auch gerne Rechte zum hochladen.

Grüße,
Jörg

**Comment by pekraem** [comment]
Hi,

ich denk jetzt müssts gehn. Ansonsten frag ich morgen mal am CN :D

**Comment by makoeppel** [comment]
Alles klar funktioniert ;) ich lade nachher meine Lösung für die 2 hoch. Jörg hat glaub was bei der 1

**Comment by makoeppel** [comment]
Jörg wenn's bei dir auch geht schließ ich das issue ;)

**Comment by JoergSchindler** [comment]
Funktioniert :)
